--- #YAML:1.0
name:               Dancer-Plugin-DirectoryView
version:            0.01
abstract:           Browse directory contents in Dancer web
author:
    - Michal Wojciechowski <odyniec@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    File::ShareDir::Install:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:          1.307
    File::ShareDir:  1
    HTTP::Date:      0
    Test::More:      0
    URI::Escape:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
